version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: Lopez04gl
      MYSQL_DATABASE: Prueba
      MYSQL_USER: LopezL
      MYSQL_PASSWORD: Lopez04gl

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"  
    
